# Generated by Django 2.0.6 on 2018-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Condition'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Disease'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor'},
        ),
        migrations.AlterModelOptions(
            name='dosage',
            options={'verbose_name': 'Dosage'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Medication'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Prescription'},
        ),
        migrations.AlterModelOptions(
            name='prescriptionentry',
            options={'verbose_name': 'PrescriptionEntry'},
        ),
        migrations.AlterModelOptions(
            name='storyentry',
            options={'verbose_name': 'Story Entry'},
        ),
        migrations.AlterModelOptions(
            name='substance',
            options={'verbose_name': 'Substance'},
        ),
        migrations.RemoveIndex(
            model_name='disease',
            name='website_dis_name_9186d8_idx',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
