# Generated by Django 2.1.2 on 2018-11-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Interaction',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
            ],
            options={
                'verbose_name': 'Refund',
            },
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Condition'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Disease'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor'},
        ),
        migrations.AlterModelOptions(
            name='dosage',
            options={'verbose_name': 'Dosage'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Medication'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Prescription'},
        ),
        migrations.AlterModelOptions(
            name='prescriptionentry',
            options={'verbose_name': 'PrescriptionEntry', 'verbose_name_plural': 'PrescriptionEntries'},
        ),
        migrations.AlterModelOptions(
            name='storyentry',
            options={'verbose_name': 'StoryEntry', 'verbose_name_plural': 'StoryEntries'},
        ),
        migrations.AlterModelOptions(
            name='substance',
            options={'verbose_name': 'Substance'},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='story',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Patient'),
        ),
        migrations.AddField(
            model_name='storyentry',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, to='website.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='refund',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Condition'),
        ),
        migrations.AddField(
            model_name='refund',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Medication'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='substance1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='website.Substance'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='substance2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='website.Substance'),
        ),
    ]
