# Generated by Django 2.1.2 on 2018-11-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181124_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, to='website.Patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('LE', 'lek.'), ('DR', 'dr n. med.'), ('DH', 'dr hab. n. med.'), ('PR', 'prof. dr hab. n. med.')], default='LE', max_length=10),
        ),
    ]
