# Generated by Django 2.1.2 on 2018-11-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181124_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['name'], name='website_dis_name_9186d8_idx'),
        ),
        migrations.AddField(
            model_name='refund',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Condition'),
        ),
        migrations.AddField(
            model_name='refund',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Medication'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='substance1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='website.Substance'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='substance2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='website.Substance'),
        ),
    ]
