# Generated by Django 2.1.2 on 2018-11-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181124_1603'),
        ('website', '0002_auto_20181124_2242'),
    ]

    operations = [
    ]
