# Generated by Django 2.1.2 on 2018-11-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181124_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptionentry',
            options={'verbose_name': 'PrescriptionEntry', 'verbose_name_plural': 'PrescriptionEntries'},
        ),
        migrations.AlterModelOptions(
            name='storyentry',
            options={'verbose_name': 'StoryEntry', 'verbose_name_plural': 'StoryEntries'},
        ),
    ]
