# Generated by Django 2.1.2 on 2018-11-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_merge_20181125_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('LE', 'lek.'), ('DR', 'dr n. med.'), ('DH', 'dr hab. n. med.'), ('PR', 'prof. dr hab. n. med.')], default='LE', max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='conditions',
            field=models.ManyToManyField(to='website.Condition'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['name'], name='website_dis_name_9186d8_idx'),
        ),
    ]
