# Generated by Django 2.1.2 on 2018-11-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20181125_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='website.Condition'),
        ),
    ]
