# Generated by Django 2.1.2 on 2018-11-25 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20181125_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionentry',
            name='refund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Refund'),
        ),
    ]
