# Generated by Django 2.1.2 on 2018-11-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20181125_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='form',
            field=models.CharField(choices=[('TB', 'tabletki'), ('ZS', 'zastrzyki'), ('KR', 'krople'), ('KP', 'kapsulki')], max_length=2),
        ),
    ]
