# Generated by Django 2.1.2 on 2018-11-25 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20181125_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionentry',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Refund'),
        ),
    ]
