# Generated by Django 2.1.2 on 2018-11-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20181125_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Condition'),
        ),
    ]
